name: DePloY
on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: ["stable", "master"]
    paths:
      - "public/**/*"
      - "src/**/*"
      - "package.json"
      - "**.js"
      - "yarn.lock"
      - "**/*.yml"
jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploying Website...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ steps.extract_branch.outputs.branch }}
            git reset --hard
            git pull
            yarn
            yarn build
            pm2 reload /home/${{ steps.extract_branch.outputs.branch }}/ecosystem.config.js --only Website-${{ steps.extract_branch.outputs.branch }}
