name: DePloY
on:
  push:
    paths:
      - "public/**/*"
      - "src/**/*"
      - "package.json"
      - "**.js"
      - "yarn.lock"
      - "**/*.yml"
jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/PreMiD/Website/${{ steps.extract_branch.outputs.branch }}
            git reset --hard
            git pull
            yarn
            yarn build
            pm2 reload /home/PreMiD/ecosystem.config.js --only Website-${{ steps.extract_branch.outputs.branch }}
