name: DePloY
on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: ["stable", "master"]
    paths:
      - "public/**/*"
      - "src/**/*"
      - "package.json"
      - "**.js"
      - "yarn.lock"
      - "**/*.yml"
jobs:
  DePloY:
    strategy:
      matrix:
        host: [1.premid.app, 2.premid.app, 3.premid.app]
    runs-on: "ubuntu-latest"
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/PreMiD/Website/${{ steps.extract_branch.outputs.branch }}
            git reset --hard
            git pull
            yarn
            yarn build
            pm2 reload /home/PreMiD/ecosystem.config.js --only Website-${{ steps.extract_branch.outputs.branch }}
